### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by yn-coder** [convergenceIM/alpha-scientist#24]

**Comment by richardbmx** [comment]
@yn-coder Hello my name is Richard I am a graphic designer and I love making contributions for open source projects, I see that you do not have a defined logo for your application. If you want I can do it for you without any problem you just have to authorize me to do it ... regards. ..

**Comment by yn-coder** [comment]
Thank you. It's a question for @convergenceIM

**Comment by convergenceIM** [comment]
Hi Richard, thanks for reaching out!  I'd be glad for contributions.  I had tried to use logojoy to generate a simple logo, but stalled out b/c it wasn't clear there was a place to put on homepage.  

The concept I was going for was simply the sitename and a simple icon which communicated science.  Here is the logo I generated:  
https://github.com/convergenceIM/alpha-scientist/blob/master/content/images/profile.jpg

which used a molecule diagram.  Also tried an atom icon, microscope, flask, etc...  Since the site has a plaintext title in the header, it probably doesn't make sense to have a version of the logo with the words in it (like the above link has).  

Instead, maybe a combination of something which evokes "science" (atom, molecule, etc...) and something which evokes "alpha".  This is most often done with the lowercase greek symbol for alpha, like [these logos](https://www.google.com/search?tbm=isch&source=hp&biw=1920&bih=974&ei=s9RDW8CxJo6z8AO5zozICw&q=alpha&oq=alpha&gs_l=img.3..0l10.2126.2707.0.2874.7.7.0.0.0.0.62.274.5.5.0....0...1ac.1.64.img..2.5.272.0...0.4nq6X9n8Ydw) show 

Side note: I'm not sure if you're familiar with quantitative finance field, but the term "alpha" means essentially profit generated from being clever (ie from outsmarting the markets rather than just making money because the markets went up in general).  The blog name "Alpha Scientist" merges the ideas of working like a "data scientist" to generate "alpha".

**Comment by richardbmx** [comment]
@convergenceIM  Based on what you request and designed this icon and logo as a basis or definitive everything depends on you. If you like it or if you want to modify something, do not hesitate to say it

![presentation90](https://user-images.githubusercontent.com/35604837/42480598-4f49b902-83ac-11e8-8cb3-90f8e7d1d928.png)

**Comment by convergenceIM** [comment]
Hi Richard, thanks for the super-quick contribution!  

Here's my commentary on the examples:
- Of those presented, I like the bottom set the most.   
- However, the molecule is a little abstract.  If I didn't already know that it was supposed to be a science/molecule theme, I wouldn't have guessed that.  
- alternatives which might be a bit more obvious would be an atom, a chemistry flask, or a DNA helix.  [This](https://www.flaticon.com/search?word=scientific%20study) is an example of science icons
- I'd ideally like to have a logo which didn't rely on words, since it'll be on the main page with the blog's title.  Perhaps just an attractive way to merge an alpha symbol with some other iconic image.  

- One kind of clever idea I've just had: a periodic table (or a small section of one) which shows the alpha as one of the elements.  See below image, which I took from flaticon (but would replace the H, Li and Be with the pi, alpha, and beta so would require graphics work.  

  Ideally alpha would be prominent, and then a couple other greek characters less bold or in a shade of grey to de-emphasize.  Other greek characters used in finance are "beta", "pi" (means profit), and lowercase sigma (variance).  

![image](https://user-images.githubusercontent.com/22535225/42553131-6b6d81e8-8494-11e8-8ff0-d4e62f314a2e.png)
 
That idea is a little involved so feel free to skip if too much.  Thanks again for your interest in helping out!

**Comment by richardbmx** [comment]
I present this second idea, guided by your idea of the periodic table but giving an original style so that it does not look the same placing the symbols so that the alpha stands out from the rest.  The intention is that it is a unique logo as you can see it can be used in the Icon version (only the icon as you wish) and in the logo version (with the letters if you want to use it in other places).

![presentation](https://user-images.githubusercontent.com/35604837/42588857-05cfb13e-850d-11e8-8ae7-70be62758f77.jpg)

**Comment by convergenceIM** [comment]
Nice, I like that design.   My primary focus is how it'll look on the banner of the current site, which has black background and some grey lettering.  

Would it be possible to make a version like the right one of the first panel except with black replaced by the same grey as on the menu bar?  So when the logo displayed on the black background in the banner, it'll have the lettering in the same black (since it's transparent) and the squares in grey.  

I think that'd look really nice!

![image](https://user-images.githubusercontent.com/22535225/42603558-2f51f614-8523-11e8-8211-81761b99e82b.png)


![](https://user-images.githubusercontent.com/35604837/42588857-05cfb13e-850d-11e8-8ae7-70be62758f77.jpg)

**Comment by richardbmx** [comment]
Perfect you annex here the version you request

Looks great

![logogris 90](https://user-images.githubusercontent.com/35604837/42605425-e2400ff0-8545-11e8-866d-8d2635b2d773.png)

**Comment by richardbmx** [comment]
You can give me the web link to make a model with logo mounted there

**Comment by yn-coder** [comment]
[alphascientist.com](https://alphascientist.com)

Thank you!

**Comment by richardbmx** [comment]
Here you can see on the web and on the favicon

![111editada](https://user-images.githubusercontent.com/35604837/42631705-fe0e312c-85a8-11e8-94a8-101c4cdda465.jpg)

**Comment by yn-coder** [comment]
It's should be @convergenceIM opinion, but I see favicon as `little black fish` :)

**Comment by richardbmx** [comment]
It can be modified in this way

The symbols pi and beta do not stand out since it was spoken that the importance is the alpha

![1112editada](https://user-images.githubusercontent.com/35604837/42632161-50f8e2f0-85aa-11e8-8b1d-37016ca43da5.jpg)

**Comment by richardbmx** [comment]
I present this version where only the alpha is incorporated into the rings of the atom

![1113editada](https://user-images.githubusercontent.com/35604837/42634391-18dac378-85b1-11e8-86b0-e599f7f464ab.jpg)

**Comment by convergenceIM** [comment]
Really nice.  I was set to say the [first one](https://user-images.githubusercontent.com/35604837/42632161-50f8e2f0-85aa-11e8-8b1d-37016ca43da5.jpg) was a winner until I saw the [second one](https://user-images.githubusercontent.com/35604837/42634391-18dac378-85b1-11e8-86b0-e599f7f464ab.jpg)

I think the second is more straightforward (obvious what the image is and the alpha is very prominent).  I'd say we go with that one.  @richardbmx, do you have a preference?  @yn-coder, do you have a preference?  

I'd agree that the first favicon seems a little hard to see.  The second one looks decent as is

**Comment by yn-coder** [comment]
I do prefere [2nd](https://user-images.githubusercontent.com/35604837/42634391-18dac378-85b1-11e8-86b0-e599f7f464ab.jpg). May be @richardbmx could rotate it contraclockwise a bit?

**Comment by richardbmx** [comment]
spin this way?

![logo33 final90](https://user-images.githubusercontent.com/35604837/42662975-a2544ade-8601-11e8-9100-54aab4362901.png)

**Comment by convergenceIM** [comment]
I think I prefer the non-rotated one.  There's something more pleasing about it (to me, anyway).  Can we go final with that?  I think this looks great :-)

**Comment by richardbmx** [comment]
Perfect prepared the archives

**Comment by richardbmx** [comment]
All file

[Google Drive](https://drive.google.com/open?id=1y3sYeRnZpjX8W0R3AzaR-aeNAwjJnzc4)

<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="License of Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is under <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons license Attribution-ShareAlike 4.0 International</a>.

**Comment by yn-coder** [comment]
@convergenceIM Ready to place it?

**Comment by convergenceIM** [comment]
Yes, let's do it.

**Comment by yn-coder** [comment]
chrome

![favicon the alpha scientist - google chrome_2018-07-13_22-56-02](https://user-images.githubusercontent.com/8451944/42711312-0d3ceaa6-86f0-11e8-8066-a7ea79598a15.png)

firefox

![favicon the alpha scientist - mozilla firefox_2018-07-13_22-57-21](https://user-images.githubusercontent.com/8451944/42711339-2d2ad15c-86f0-11e8-9f54-5f0c9f073b01.png)

**Comment by convergenceIM** [comment]
Favicon looks great.  I am not seeing the banner logo yet.  Does that require SASS changes?  If so, would you mind documenting the steps you needed to follow as an example for what I'd need to do to make similar changes to the css in future?

**Comment by yn-coder** [comment]
baner is not ready yet

no, css is not changing. But I've write down the sass recompiling quest

**Comment by yn-coder** [comment]
@richardbmx could you please help me with right html code from your sample?

```
  <header role="banner"><hgroup>
  <img src="./images/logo.png" width="100" height="40">
  <h1><a href="./">The Alpha Scientist</a></h1>
    <h2>Discovering alpha in the stock market using data science</h2>
</hgroup></header>
```

What file we need to use? logo90.png?

**Comment by richardbmx** [comment]
yes logo90.png

**Comment by yn-coder** [comment]
@richardbmx can you show your html block for logo?

**Comment by richardbmx** [comment]
@yn-coder I do not know anything about hmtl

**Comment by yn-coder** [comment]
:) you've just placed the logo in picture editor?

**Comment by richardbmx** [comment]
no it was not me

**Comment by yn-coder** [comment]
@convergenceIM here is a sample for  header with logo

Commit?

![the alpha scientist - google chrome_2018-07-14_01-13-03](https://user-images.githubusercontent.com/8451944/42716205-1a6b9bec-8703-11e8-90c3-9cff13b8355e.png)

**Comment by richardbmx** [comment]
I think you have to make the color a little bit lighter ...

I'm going to modify it and load it again

**Comment by richardbmx** [comment]
Logo new color [logo](https://drive.google.com/open?id=10GtCpHormu-yUjEG8y8G1xl1YqZLp0Ql)

**Comment by yn-coder** [comment]
here is!

![the alpha scientist - google chrome_2018-07-14_01-39-04](https://user-images.githubusercontent.com/8451944/42716964-c9294e1a-8706-11e8-9fee-ab1ce270df40.png)

**Comment by richardbmx** [comment]
perfect!!

**Comment by yn-coder** [comment]
@convergenceIM Publish it?

**Comment by yn-coder** [comment]
Close it?

**Comment by convergenceIM** [comment]
Yes, closing.  It looks great
